### PR TITLE
Updating new-note and collaborate icons.

### LINKED ISSUE #1103: Update Simplecons icons
Update `new-note` and `collaborate` icons from https://github.com/Automattic/Simplecons as mentioned in p2XJRt-2CV

### PR DESCRIPTION
**Pull request by illusaen**
Fixes #1103 

### Fix
Updating `new-note` and `collaborate` icons with the new PDFs found in https://github.com/Automattic/Simplecons.

#### New note
1. Open Simplenote.
2. See new icon on top left.

#### Collaborate
1. Open Simplenote.
2. Go to note.
3. Click Options button on top right.
4. See new icon on Collaborate cell.

### Screenshots
Simulator Screen Shot - iPhone 12 mini - 2021-02-09 at 17 03 23

Simulator Screen Shot - iPhone 12 mini - 2021-02-09 at 17 03 38

### Review
Only one developer and one designer are required to review these changes, but anyone can perform the review.

### Release
`RELEASE-NOTES.txt` was updated in be459c2 with:
Updating new-note and collaborate icons #1103

### CODE REVIEW

**Comment by mokagio** [comment]
@illusaen Thank you for opening this PR.

I took the liberty of updating the images in your PR description to be smaller. Otherwise, we'd end up with something that takes up a lot of space and makes the description harder to read.

image

Here's another tip: when opening PRs that update visuals, it's handy to have a "before and after" comparison



[source](https://twitter.com/mokagio/status/1019709696872087557)

**Review by mokagio — APPROVED** [review]
I can't see any difference visually which is not surprising as mentioned [in the internal ref for this work](https://wp.me/p2XJRt-2CV), but I `diff`ed the PDFs in this branch with the ones in Simplecon and they match, so 👍 from me.

Looping in @SylvesterWilmott just in case you want to see the new icons on device first.

_P.S. @illusaen, while I'm always happy to review PRs (in particular if there are questions about testing) you're likely better off asking @eshurakov and @jleandroperez for a review of the Simplenote iOS code._ 😄

**Comment by illusaen** [comment]
> P.S. @illusaen, while I'm always happy to review PRs (in particular if there are questions about testing) you're likely better off asking @eshurakov and @jleandroperez for a review of the Simplenote iOS code. 😄

Makes sense, thanks! :) I was definitely just clicking the "Recommended" person, haha, so that's very helpful.

**Comment by illusaen** [comment]
> @illusaen Thank you for opening this PR.
> 
> I took the liberty of updating the images in your PR description to be smaller. Otherwise, we'd end up with something that takes up a lot of space and makes the description harder to read.
> 
> Here's another tip: when opening PRs that update visuals, it's handy to have a "before and after" comparison
> 

Will do, thanks much!

**Comment by SylvesterWilmott** [comment]
Looks good to me! Thanks!

**Comment by jleandroperez** [comment]
@mokagio You're a rockstar!!!

@illusaen Thank you for updating the assets!!

🔥 🔥 🔥

**Comment by pachlava** [comment]
[testing] fix/feature verified on iPhone XR | iOS 14.4 | Simplenote 4.33.0.0

**Pull request merged**
