### PR TITLE
Tags Cell: UX Refresh!

### PR DESCRIPTION
**Pull request by jleandroperez**
### Details:
In this PR we're refining the Tag Cell UX, to match the latest Advanced Search Mockups:

- New Tag icon on the left hand side
- And since we were there... the `SectionsHeader` got few fixes for iPad

cc @bummytime (Thaaankyouuuu)
cc @SylvesterWilmott for UX review (screenshots attached in a file, belooow, LOTS of them).

Ref. #507

### Test
1. Launch Simplenote
2. Trigger a Search OP that yields both Notes and Tags

- [x] Verify the Tag Cells look great
- [x] Verify that the app reacts well to different Dynamic Typing settings
- [x] Verify the Section Header (`Search by Tags` and `Notes` in Search Mode) looks great
- [ ] Verify no Console Warning shows up the second you type a Search Keyword

Please test on iPhone and iPad Devices

### Release
These changes do not require release notes.

### Screenshots:
[Screenshots.zip](https://github.com/Automattic/simplenote-ios/files/4134967/Screenshots.zip)

### CODE REVIEW

**Comment by bummytime** [comment]
I reset the sim and full clean + rebuild as well. 🤔

**Comment by SylvesterWilmott** [comment]
Looks good @jleandroperez Thanks

There seems to be a small bug with the touch feedback on the list.

Tap and hold on an item:

Screenshot 2020-02-03 at 15 39 31

Also, I am not able to capture a similar bug with the notes list because it's a short flash, but it's there. When tapping a note row from the search screen there are white sections on the blue touch feedback.

Otherwise, everything looks great

**Comment by jleandroperez** [comment]
- Section HeaderFooter Warning fixed
- And also fixed the TagTableViewCell's highlight (solid white)

Thank you @SylvesterWilmott + @bummytime !! Ready for another look!

🔥

**Comment by bummytime** [comment]
@jleandroperez Thank you for the updates. This PR can :shipit: !

As an aside, on my iPhone 11 Pro (iOS 13.3), I noticed the bottom tags bar would remain "high" after dismissing the search footer:

tags_iOS13_iPhone11Pro

Not sure if you are aware of this already or not. :-)

**Comment by jleandroperez** [comment]
Nice catch!! Added a note in the main issue, I'll get that fixed in another PR.

Thank you Bummy!!

**Pull request merged**
