### PR TITLE
Update Tag Menu to New Design

### PR DESCRIPTION
**Pull request by roundhill**
Updates the tag drawer/menu to the new design as outlined by @drw158. It ended up changing quite a few things about how the code works in `SPTagsListViewController` mainly:
- The UITableView `edit` process no longer expands the tableview to full screen, instead you edit the tags list in place (see screenshots)
- The TableView now only uses one section (yay!), but it requires a lot of views for the headers and footers to be created in the code (boo!). I think it's actually a bit less complex now which is nice.

Also, a view was needed to be added to `SPNoteListViewController` to show a border at the left side when the drawer is opened. (See `SPBorderedTableView`)

I really wanted a storyboard/swift conversion for this, but didn't have the time so stuck with good ol' Obj-c. 😬

Screenshots:
simulator screen shot oct 28 2016 2 28 11 pm
simulator screen shot oct 28 2016 2 28 15 pm
simulator screen shot oct 28 2016 2 30 07 pm

@jleandroperez needs review! Thanks!

### CODE REVIEW

**Comment by drw158** [comment]
Cool! looks good. Only issue I can think of is maybe editing the tags in that small space would be cramped, but would have to interact with it for real. If that is the case, I could see the sidebar getting a little bit wider, just in edit mode. But, maybe there's enough room already.

**Comment by roundhill** [comment]
I noticed that the divider between the top toolbar and the other dividers is a different color. I'll investigate how to update that.

**Comment by jleandroperez** [comment]
@roundhill i've changed few things here and there, and moved some numbers to constants.

Please, make sure i didn't break anything, and :shipit: once ready!

Nice work Dan!!!

**Comment by roundhill** [comment]
Thanks @jleandroperez 

> If that is the case, I could imagine the sidebar getting a little bit wider, just in edit mode.

@drw158 I think I'll attempt this, it is a bit awkward to edit the tags in such a small space.

**Comment by roundhill** [comment]
@jleandroperez I've added a bunch of new changes, I think it's ready for another look :)

* Tags list will become wider in edit mode
* Updated png resources to match new color scheme
* Fixed some keyboard layout oddities

**Comment by jleandroperez** [comment]
Looks great @roundhill, nice job!!

:shipit:

**Pull request merged**
