### PR TITLE
Alphabetize note tags

### PR DESCRIPTION
**Pull request by khoiln**
#21

### CODE REVIEW

**Comment by jleandroperez** [comment]
Hello there @khoiln!!

Thanks for the PR, but this is actually by design. Tags can be arranged by hand, and the order is expected to be reflected in all of the devices.

**Comment by khoiln** [comment]
Oops sorry I didn't know that :).

**Comment by jleandroperez** [comment]
No worries sir!! thanks for helping us out!!

**Comment by supernovia** [comment]
@jleandroperez it occurs to me people may be asking about the ability to alphabetize by title, actually, since the word "tags" appears above the list of titles with an arrow. Maybe people think the arrow means "These things below are tags" when they are in fact note titles, and the arrow is there to indicate options for tags.

**Comment by jleandroperez** [comment]
@supernovia i'm sorry i've missed that ping!! ^^

Not sure to which app you refer to, can't see any arrows in the iOS app. Maybe the macOS one?. Still, Simplenote already has an option that automatically **Sorts Notes Alphabetically** (Open the Tags area, bottom button `Settings`, it should be at the top).

In the macOS app, such option is available via **View >> Sort Notes Alphabetically**.

Thanks for the feedback!!

**Pull request closed without merging**
