### PR TITLE
Magic Links: Limit character input on login code text field

### PR DESCRIPTION
**Pull request by charliescheer**
### Fix
We recently implemented code authentication into Simplenote.  One thing we were concerned about is what would happen if someone put in a huge amount of characters into the code field input.  Nothing should happen, but it seemed like a good idea to limit the character count to on the code input text field.

So in this PR I have done just that

### Test
***(Required)*** List the steps to test the behavior.  For example:
1. Fresh install Simplenote.  Go to login and enter your email
2. when the code input appears, attempt to put in more characters than the code limit of 6

- [ ] Confirm you can only put 6 characters in the code field 
- [ ] Confirm that the username and password fields do not have a limit in them

### Review
***(Required)*** Add instructions for reviewers.  For example:
> Only one developer is required to review these changes, but anyone can perform the review.

### Release
***(Required)*** Add a concise statement to `RELEASE-NOTES.txt` if the changes should be included in release notes. Include details about updating the notes in this section. For example:
> These changes do not require release notes.

### CODE REVIEW

**Review by jleandroperez — APPROVED** [review]
:shipit:

**Comment by mokagio** [comment]
@charliescheer I merged `trunk` after landing #1634. CI should now work.

I changed the Buildkite pipelines settings to require explicit `agents` and made the change to comply in the release branch. I was assuming I'd merge the release branch promptly, but that wasn't the case. 

Sorry for the trouble.

**Comment by mokagio** [comment]
@charliescheer I can see this PR has the "Future" milestone, but just wanted to confirm the change was not meant to go in the 4.52 beta.

**Comment by charliescheer** [comment]
@mokagio it does not need to go into the 4.52 beta.  This change can be in the next release

**Pull request merged**
