### PR TITLE
Spotlight: Handling App Upgrades

### PR DESCRIPTION
**Pull request by jleandroperez**
### Details:
In this PR we're adding a simple mechanism to index all of the user's notes, whenever he upgrades from an older App version.

We're also bumping up the Simperium dependency to its latest version.

### Testing:
1. Check out develop [at this precise point](https://github.com/Automattic/simplenote-ios/commit/896de09703e1611ef50350a165560b2f865c67ca). (Reason: Spotlight was not supported there!)
2. Fresh install the app and log into your account
3. Install this branch (`issue/spotlight-upgrade-path`) on top of it
4. Verify that your notes were effectively indexed

@roundhill you game for a review?

cc @michalkosmowski  (Again, thank you Michal!)

### CODE REVIEW

**Comment by alaskaa30** [comment]
issue/spotlight-upgrade-path)

**Comment by roundhill** [comment]
I think this wasn't caught in the Spotlight PR, but I have a note with a single emoji in it(the fire one: 🔥). 

The crash is here: https://github.com/Automattic/simplenote-ios/blob/issue/spotlight-upgrade-path/Simplenote/Classes/CSSearchable%2BHelpers.swift#L21

Out of index exception most likely...

**Comment by jleandroperez** [comment]
@roundhill may i bug you with a quick check?. All should be good now!

Thanks Dan!!!

**Comment by michalkosmowski** [comment]
Ugh, so `emoji.utf16.count` returns `2`.
Nice catch @roundhill 🔥

**Comment by roundhill** [comment]
Tested again, working great with the upgrade flow 👍 

:shipit:

**Comment by jleandroperez** [comment]
Thanks for the review Dan!

**Pull request merged**
