### PR TITLE
Adding Existing Rake Binary of SwiftLint to Xcode

### PR DESCRIPTION
**Pull request by illusaen**
See #1141 for linting changes, as well as first iteration of adding SwiftLint via Cocoapods.

### Fix
Adds SwiftLint to Xcode project via ~~Swift Package Manager~~ existing rake binary.

~~*NOTE* that this solution requires an added `Package.swift` dummy file in order to load the dependency.~~

### Test
1. Load Xcode project.
2. Build.
3. See that any linting errors show up on Build Issues tab on sidebar.

### Screenshots
Screen Shot 2021-02-09 at 8 44 43 PM

### Review
Only one developer and one designer are required to review these changes, but anyone can perform the review.

### Release
These changes do not require release notes.

### CODE REVIEW

**Comment by eshurakov** [comment]
The project already has a SwiftLint binary that is installed via `rake`. Do you think we can use or extend it?
https://github.com/Automattic/simplenote-ios#swiftlint

**Comment by illusaen** [comment]
> The project already has a SwiftLint binary that is installed via `rake`. Do you think we can use or extend it?
> https://github.com/Automattic/simplenote-ios#swiftlint

You... are a genius. I 100% missed that `rake` was installing that executable.

**Review by jleandroperez — COMMENTED** [review]
@illusaen Thank you for doing this!

Two nipticky notes: would you mind renaming the Build Phase`Run Script` to something a bit more descriptive?

**Plus:** WooCommerce runs this [Swift Linting Script](https://github.com/woocommerce/woocommerce-ios/blob/develop/Scripts/build-phases/swiftlint.sh), which only picks up modified files (so that should lower the runtime.

Do you think we cooould maybe "borrow" that one?

Thank you!!

**Comment by illusaen** [comment]
> ...would you mind renaming the Build Phase`Run Script` to something a bit more descriptive?
> 
> **Plus:** WooCommerce runs this [Swift Linting Script](https://github.com/woocommerce/woocommerce-ios/blob/develop/Scripts/build-phases/swiftlint.sh), which only picks up modified files (so that should lower the runtime.
> 
> Do you think we cooould maybe "borrow" that one?
> 

Done! Took the WooCommerce script and modified it for our use :)

**Review by eshurakov — APPROVED** [review]
Nice work! Thank you 👍 

:shipit:

**Pull request merged**
