### PR TITLE
Extended Debugging

### PR DESCRIPTION
**Pull request by jleandroperez**
### Details:
This PR adds an "Extended Diagnostics Mode" to the Authentication Interface.

cc @SylvesterWilmott What do you think? (Hackweek Project!!)

@etoledom Eduardoo!!! Can I bug you with a fun (easter egg) PR?

Thank youuu!!

### Test
1. Fresh Install Simplenote
2. **Triple Tap** over the Simplenote Logo

- [x] Verify that an alert saying `Debug Enabled` shows up
- [x] Verify that triple-tapping again triggers a `Debug Disabled` alert

### Test: Diagnostics
1. Fresh Install Simplenote
2. **Triple Tap** over the Simplenote Logo
3. Press over **Log In > Log In with Email**
4. Set your phone in Airplane Mode
5. Enter any random credentials and **press Login**

- [x] Verify a new UI shows up, with extra debug details
- [x] Verify that pressing `Share` shows the standard System's Share Sheet
- [x] Verify that pressing `Done` dismisses the Diagnostics UI

### Release
These changes do not require release notes.

---

### CODE REVIEW

**Comment by SylvesterWilmott** [comment]
:shipit:

**Comment by jleandroperez** [comment]
Thanks for checking this @SylvesterWilmott !!

**Review by etoledom — APPROVED** [review]
This is great! 🎉 

Nice Hack Week project, works like a charm ✨

**Comment by jleandroperez** [comment]
Thanks a million @etoledom !!!

**Pull request merged**
