### PR TITLE
Spring Cleaning: Refreshing Note Cell

### PR DESCRIPTION
**Pull request by jleandroperez**
### Details:
This PR is part of a (multistep) effort to deduplicate manual layout code, spread in few areas. 
We're **also** updating the Notes Cell, so that the Pinned icon is displayed on the right hand side.

Gentlemen, may I bug you all with yet another Autlayout PR?
🔥 

cc @danielebogo @aerych @etoledom 

See you all tomorrow!!!
Ref. #408 

### Testing:
In each device, please, verify the following:

- Dark Mode
- Transition between List > Editor
- And please make sure the UI matches the mockups in #408 (right hand side should display either Pinned or Shared state).

#### cc @danielebogo  (Thanks in advance Daniele!!!)👇
- [x] iPhone SE (Portrait)
- [x] iPhone SE (Landscape)
- [x] iPhone 8 (Landscape)
- [x] iPhone 8 (Portrait)
- [x] iPad Multitasking 1/3 (Landscape)

#### cc @etoledom  (Thank you Eduardo!!!)👇
- [x] iPhone 8+ (Landscape)
- [x] iPhone 8+ (Portrait)
- [x] iPhone Xs (Portrait)
- [x] iPhone Xs (Landscape)
- [x] iPad Multitasking 1/2 (Landscape)

#### cc @aerych (Thank you Eric!!!) 👇
- [x] iPhone Xs Max (Landscape)
- [x] iPhone Xs Max (Portrait)
- [x] iPad Fullscreen (Portrait)
- [x] iPad Fullscreen (Landscape)
- [x] iPad Multitasking 2/3 (Landscape)

### Release
`RELEASE-NOTES.txt` was updated in 977cdf9 with:

> Notes List refreshed to display Pinned state on the right hand side.

### CODE REVIEW

**Comment by aerych** [comment]
Hey @jleandroperez!  I tried deleting the app from the simulator and cleaning the build folder, then reinstalled.  I still see the same alignment as before.  Just to be clear tho, those are icons on different notes.  When I pin and share a single note I do see them laid out horizontally, but there is still the cropping on the iPad and the not quite aligned right edge on the iPhone. Like so: 
Screen Shot 2019-09-13 at 9 41 49 AM

**Comment by jleandroperez** [comment]
@aerych **THANK YOU** for the extremely detail focused review, **MUCH MUCH MUCH** appreciated!!!

**Comment by jleandroperez** [comment]
Ping @danielebogo @etoledom (YES we owe you both t-shirts!! LOL) 😂

**Comment by etoledom** [comment]
Will review as soon as possible! Hopefully tomorrow 👍

**Comment by jleandroperez** [comment]
Thank you @etoledom !!!

Aye the login screen is light on purpose. As per the scrollbar I'll check if that can be patched up in another PR.

Thanks everyone!!!

**Pull request merged**
