### PR TITLE
Delete note if the content is completely removed

### PR DESCRIPTION
**Pull request by charliescheer**
### Fix
It was brought up in an [issue for SNMac](https://github.com/Automattic/simplenote-macos/issues/1064), that if a note is empty we leave it in the note list and it would be nice if they deleted themselves.  I thought about this for a bit and decided that I agreed, but I wanted to make sure that we only moved the notes to the trash, that way the history for the note still exists and a user could reclaim the lost content if they wanted.  So in this PR I have done that.

iOS already deleted _new_ notes that were empty, so this PR simply updates that logic to not exclude existing notes.  If a user deletes all the content in a note and then exits the editor the note will be moved to the trash.  This is the same behavior as in apple notes.

#### Confirm new notes with content are not deleted ####
1. Create a new note and add some content to it
2. Close the editor
- [ ] Confirm your new note continues to exist
- [ ] Relaunch the app and confirm your new note was saved to the DB

#### Confirm new notes without content are deleted ####
1. Create a new note, do not add content to it
2. Close the editor
- [ ] Confirm that your new note was deleted

#### Confirm an existing note that has all it's content removed, will be deleted ####
1. Go to a note you don't mind losing.
2. Delete all of the text content in the note
3. Exit the editor.
- [ ] Confirm that your note is deleted from the notes list

4. Go to the note trash, find the top note labeled "New Note..." restore it
5. Go to the regular notes list, open the note you restored, go to the notes history
- [ ] Confirm you can restore that notes history

### Review
***(Required)*** Add instructions for reviewers.  For example:
> Only one developer and one designer are required to review these changes, but anyone can perform the review.

### Release
***(Required)*** Add a concise statement to `RELEASE-NOTES.txt` if the changes should be included in release notes. Include details about updating the notes in this section. For example:
> These changes do not require release notes.

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is assigned to the milestone <a href="https://github.com/Automattic/simplenote-ios/milestone/71">4.56</a>. This milestone is due in less than 4 days.<br />
Please make sure to get it merged by then or assign it to a milestone with a later deadline.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by jleandroperez** [comment]
@charliescheer I'm not 100% sure this change is what we want: you'd loose the ability to use the Revision History slider to recover the content. 

The note would end up in Trash, so you'd need to manually recover, **before** you're able to use the version slider.

WDYT?

**Review by jleandroperez — APPROVED** [review]
:shipit:

**Comment by charliescheer** [comment]
After discussing this, we have decided not to make these changes.  Closing this PR

**Pull request closed without merging**
