### PR TITLE
Update rake to fix a CVE

### PR DESCRIPTION
**Pull request by jkmassel**
Fixes _another_ warning, this one caused by `rake`.

**To Test**
1) Ensure all tests are passing
2) Check out this branch and run `rake dependencies`
3) Everything should work great.

### CODE REVIEW

**Comment by loremattei** [comment]
This works and fixes the warning, though `rake dependencies` (which is what we always do) runs the system wide `rake` and not the one installed by `bundler`.

I looked at the CI scripts and it seems that we don't use rake there. So I wonder if we should just remove it from the `Gemfile`.

**Comment by jkmassel** [comment]
Hmm – maybe my system is configured differently 🤔 

When using `rbenv`, it automatically uses the bundled `rake` if possible (again, at least on my machine):

```
## in ~/.../simplenote-ios
rake --version #rake, version 12.3.3

## in ~
rake --version #rake, version 12.3.2
```

IMHO, ideally we'd avoid relying on system `rake` even being present, especially given that future macOS versions won't come bundled with it, but WDYT?

**Comment by loremattei** [comment]
Mmm... this is interesting. 
```

**Comment by jkmassel** [comment]
Replaced by https://github.com/Automattic/simplenote-ios/pull/699.

**Pull request closed without merging**
