### PR TITLE
Merge Release/4.14 into develop

### PR DESCRIPTION
**Pull request by loremattei**
Merge Release/4.14 into develop

These changes do not require release notes.

### CODE REVIEW

**Comment by jleandroperez** [comment]
@loremattei Sir!! I think something may be broken in the script that updates the translations.

CI is breaking, I've nailed it down to [this commit](https://github.com/Automattic/simplenote-ios/commit/faf178816eaf525e793b995cd0110564b743bb1e) (`Updates translation`).

There seem to be a couple malformed comments, such as [thsi one](https://github.com/Automattic/simplenote-ios/commit/faf178816eaf525e793b995cd0110564b743bb1e#diff-3b7b25e36041b92df2bf9295f6746accR33) (and few multiline strings breaking).

**Comment by jleandroperez** [comment]
@loremattei Translations Scripts **should be** [fixed here](https://github.com/Automattic/simplenote-ios/pull/545).

Thank you!!!

**Comment by loremattei** [comment]
Oh! Thank you @jleandroperez! I started looking into it and built a good binary, but then had to log off for a while a forgot to mark this PR as not ready 😅.
Thanks for having looked into this and fixed it!

**Comment by jleandroperez** [comment]
@loremattei Actually **you sir** fixed this in WPiOS, I simply replicated your script over here!! ❤️

**Comment by loremattei** [comment]
Oh! Thank _you_ sir! 🙌

**Pull request merged**
