### PR TITLE
Interlinking: Navigation Support

### PR DESCRIPTION
**Pull request by jleandroperez**
### Details:
- Adds Interlink Navigation Support: `simperium://note/KEY`
- Interlinks in the Note Editor and Markdown Preview are now handled!
- EditorViewController is now disposable: the AppDelegate no longer keeps a reference to it!
- Few State Restoration changes, to support the new Editor changes

@aerych you game for a fun PR?
Thank you sir!!

Ref. #863

### Scenario: Editor Navigation
1. Swipe over any Note row in the Notes List
2. Press the Link button
3. Open any random note and paste the link you've copied in (2)
4. Paste the link
5. Dismiss the keyboard

- [x] Verify the "Target Note" `simplenote://...` link gets linkified
- [x] Verify that long pressing over such link pushes a new editor, with the target document
- [x] Verify that the **Back** button gets you to the Notes List

### Scenario: Markdown Navigation
1. Repeat the exact same steps as in the `Editor Navigation` scenario
2. Enable Markdown Preview, and swipe to access the Preview mode
3. Press over the link you've pasted in (3)

- [x] Verify the "Target Note" shows up Onscreen
- [x] Verify the animation looks like a regular navController Push
- [x] Verify that the **Back** button gets you to the Notes List

### Scenario: Regressions
- [x] Verify that State Restoration can bring back the note that was previously edited
- [x] Verify the Editor's History feature still works as expected
- [x] Verify that Logout also works well
- [x] Verify that updating remotely a note works as expected
- [ ] Verify that deleting a note (remotely) while the Editor is onscreen triggers an alert (Please **also** empty the Trash!!)

### Release
`RELEASE-NOTES.txt` was updated in b34cab2 with:

> Long Pressing over an Internal Link now pushes the target Note

### CODE REVIEW

**Comment by mokagio** [comment]
Pushed this to 4.25 because it's code freeze time for 4.24.

**Comment by jleandroperez** [comment]
@aerych I've wired your `EditorFactory` approach, love it!!

BTW regarding this test scenario:

```
Verify that deleting a note (remotely) while the Editor is onscreen triggers an alert
```

I forgot to mention, you'd need to empty the Trash as well (just deleting isn't enough!). Updating the issue description as well.

Thanks again sir!!

**Comment by aerych** [comment]
> you'd need to empty the Trash as well

There we go!  Thank ya sir.
Simulator Screen Shot - iPhone SE (2nd generation) - 2020-09-07 at 10 27 11

Changes look great @jleandroperez!  :shipit:

**Review by aerych — APPROVED** [review]

**Comment by jleandroperez** [comment]
Thank you @aerych !!!

**Comment by mokagio** [comment]
Hey @jleandroperez. Should we deploy a new beta of 4.24 to incorporate this change?

**Comment by jleandroperez** [comment]
(Just for the record!) we're pushing back Interlinking to 4.25 (PR #873). I'll ping you in that other PR as soon as it's approved.

Thank you sir!!

**Pull request merged**
