### PR TITLE
Enforce use of bundle exec in Fastfile+Podfile

### PR DESCRIPTION
**Pull request by AliSoftware**
### Fix

This adds checks in the `Fastfile` and `Podfile` so that it stops you from accidentally run `fastlane` or `pod` without prefixing them with `bundle exec`.

If you forget to prepend `bundle exec` when invoking `fastlane` or `pod`, this will now error and stop, telling you to use `bundle exec` – so you run the versions of those tools specified in the repo's `Gemfile.lock` – instead of continuing to run with the system-wide version – which might not be the same and behave differently than when ran under bundle exec.

### Test

1️⃣  Run `pod install` and see it fail.

<details><summary>Expected pod failure when running without <tt>bundle exec</tt></summary>

```
[!] Invalid `Podfile` file: Please run CocoaPods via `bundle exec`.

 #  from /Users/olivier/Documents/Dev/simplenote-ios/Podfile:4
 #  -------------------------------------------
 #  unless ['BUNDLE_BIN_PATH', 'BUNDLE_GEMFILE'].any? { |k| ENV.key?(k) }
 >  	raise 'Please run CocoaPods via `bundle exec`'
 #  end
 #  -------------------------------------------
```

(Note: Sadly there is no way to avoid the stacktrace from showing, which might make you think there is a syntax error in the Podfile while the syntax is correct and it just shows where the exception was raised)
</details>

2️⃣ Run `bundle exec pod install` (or `be pod install` if you created an alias for `bundle exec` in your `.zshrc`, which I recommend) and check that it runs as expected

3️⃣ Run `fastlane lanes`, and check it fails with the following output

<details><summary>Expected fastlane failure when running without <tt>bundle exec</tt></summary>

```
[✔] 🚀 
[20:04:41]: fastlane detected a Gemfile in the current directory
[20:04:41]: However, it seems like you didn't use `bundle exec`
[20:04:41]: To launch fastlane faster, please use
[20:04:41]: 
[20:04:41]: $ bundle exec fastlane lanes
[20:04:41]: 
[20:04:41]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[20:04:42]: Installing Ruby gem 'fastlane-plugin-wpmreleasetoolkit'...
[20:04:58]: Found gem "fastlane-plugin-release_helper" instead of the required name "fastlane-plugin-wpmreleasetoolkit"
[20:04:59]: Successfully installed 'fastlane-plugin-wpmreleasetoolkit'
[20:04:59]: Error loading plugin 'fastlane-plugin-wpmreleasetoolkit': cannot load such file -- fastlane/plugin/wpmreleasetoolkit
+-----------------------------------+-----------+--------------------------------------------------+
|                                           Used plugins                                           |
+-----------------------------------+-----------+--------------------------------------------------+
| Plugin                            | Version   | Action                                           |
+-----------------------------------+-----------+--------------------------------------------------+
| fastlane-plugin-wpmreleasetoolkit | undefined | No actions found                                 |
| fastlane-plugin-sentry            | 1.6.0     | sentry_upload_dsym sentry_set_commits            |
|                                   |           | sentry_upload_sourcemap sentry_finalize_release  |
|                                   |           | sentry_upload_file sentry_upload_proguard        |
|                                   |           | sentry_create_release                            |
| fastlane-plugin-appcenter         | 1.8.0     | appcenter_fetch_version_number                   |
|                                   |           | appcenter_fetch_devices appcenter_upload         |
+-----------------------------------+-----------+--------------------------------------------------+

[!] No actions were found while loading one or more plugins
    Please use `bundle exec fastlane` with plugins
    More info - https://docs.fastlane.tools/plugins/using-plugins/#run-with-plugins

[20:05:00]: ------------------------------
[20:05:00]: --- Step: default_platform ---
[20:05:00]: ------------------------------

[!] Please run fastlane via `bundle exec`
```
</details>

4️⃣ Run `bundle exec fastlane lanes` and check that it runs without issues and lists the available lanes

### Review

Only one developer is required to review these changes, but anyone can perform the review.

### Release

These changes do not require release notes.

### CODE REVIEW

**Review by jkmassel — APPROVED** [review]
Weirdly on my machine the `fastlane` call printed

```
[!] No actions were found while loading one or more plugins
    Please use `bundle exec fastlane` with plugins
    More info - https://docs.fastlane.tools/plugins/using-plugins/#run-with-plugins
```

but didn't crash - it still showed me the lanes. this might be specific to my machine?

Either way, I don't think it's a blocker unless it's happening to others as well.

**Review by mokagio — APPROVED** [review]
`pod install` | `fastlane lanes`
--- | ---
image | image

:shipit:

**Comment by mokagio** [comment]
@jkmassel that's odd 🤔

**Comment by AliSoftware** [comment]
@jkmassel do you maybe have a that zsh plugin that auto-prepends `bundle exec` for you transparently when you call `fastlane`? Would explain why it didn't crash… though it wouldn't explain why it still prints fastlane's own message suggesting you to use bundle exec.
What's your `fastlane env` output?

**Pull request merged**
