### PR TITLE
Crash: tableView Out of Sync

### PR DESCRIPTION
**Pull request by jleandroperez**
### Fix
In this PR we're aiming at fixing a UITableView Out of Sync exception, caused by (alledgedly) the NoteListController falling OOS with the underlying database.

As per Apple Docs on `fetchedObjects` FRC property:

> The results array reflects the in-memory state of managed objects in the controller’s managed object context, not their state in the persistent store. The returned array does not, however, update as managed objects are inserted, modified, or deleted.

We're receiving crashlogs indicating that the Notes List's TableView doesn't match the DataSource state (right after being updated by the FRC delegate methods).

Only way (so far) I could come up, to explain this, is that the `ResultsController` is informing the wrong numberOfObjects / `fetchedObjects`.

#### Details:
- Replaced `ResultsController.fetchedObjects` usage with `ResultsController.sections.objects`
- Renamed `ResultsController.fetchedObjects` > `ResultsController.retrievedObjects`
- `NotesListState` now conforms to Equatable (and dropped unneded code!)
- Updated few Unit Tests

@astralbodies May I bug you with this one sir?

Thaaank youuu!!!

Ref. #730

### Test
- [ ] Verify the Unit Tests look great
- [ ] Verify the changes make sense
- [ ] Verify the Notes List displays your notes
- [ ] Verify Notes can be randomly accessed
- [ ] Verify Search yields Tags / Notes, and both can be pressed without further issues

### Release
These changes do not require release notes.

### CODE REVIEW

**Comment by mokagio** [comment]
@jleandroperez this has milestone 4.19 but is still in draft. 

I'm starting the code freeze for 4.19 now. Let me know whether you want to base it off the release branch or shift this for 4.20. Thanks 😄

**Comment by jleandroperez** [comment]
hi there @mokagio ! Since this one (attempts to) fix a crasher, it'd probably be a good idea to ship it ASAP. Remapping to 4.19, we'll prooobably need to bug you once it's merged.

Thank you and apologies about the fuzz!!

**Comment by mokagio** [comment]
@jleandroperez thought so. No worries at all 👍 

I'm subscribed to this issue, so I'll know when it's merged. I can release a new beta with this if you think it'll help evaluate the fix with the beta users.

**Comment by jleandroperez** [comment]
Thank you @mokagio !!

**Comment by jleandroperez** [comment]
Closing this one. As pointed out by @astralbodies, the docs actually state that the array returned by `FRC.fetchedObjects` isn't updated by itself, but calling `fetchedObjects` again should return a fresh snapshot.

Back to the whiteboard stage, I'm afraid this one will have to wait for the next release.


Thank you @astralbodies !!! (and thank you as well @mokagio !!)

**Pull request closed without merging**
