### PR TITLE
Nü passcode screen: III

### LINKED ISSUE #761: Nü Passcode
### Guidelines
- New code should always be Swift
- Autolayout **is always preferred**
- Please drop outdated components when appropriate! 🔥🔥🔥

### Details
- [ ] Encapsulate all of the Pincode support (currently spread in the AppDelegate)
- [ ] Encapsulate our FaceId + TouchID support
- [ ] Unit Test all the things
- [ ] Implement the new Passcode UI
- [ ] Please keep the Attempts Limit logic

### PR DESCRIPTION
**Pull request by eshurakov**
### Fix
In this PR we're replacing the old screen to turn off a passcode with a new shiny one. When you try to turn off a passcode from the settings screen you will see a new passcode screen instead of the old one.

In addition passcode screen is always shown in portrait on iPhone to have enough space to show a number pad.

Related issue: #761

|||
|-|-|
|Simulator Screen Shot - iPhone 12 - 2021-01-05 at 10 00 57|Simulator Screen Shot - iPhone 12 - 2021-01-05 at 10 00 42|
|Simulator Screen Shot - iPad Pro (9 7-inch) - 2021-01-05 at 09 57 34|Simulator Screen Shot - iPad Pro (9 7-inch) - 2021-01-05 at 09 57 43|

### Test (Turn off passcode)
1. Set a passcode
2. Open Settings
3. Tap on Passcode

- [x] Turn off passcode screen is presented
- [x] Passcode screen can be dismissed using "Cancel" button
- [x] Passcode screen can't be dismissed by pulling it down
- [x] Entering incorrect passcode shakes the header and shows an error message with the number of attempts
- [x] Entering correct passcode dismisses the screen and passcode row says "off"

### Test (Rotation on iPhone)
1. Rotate iPhone into landscape
2. Open Settings -> Passcode

- [x] Check that passcode screen is opened in portrait

### Test (Rotation on iPad)
1. Open Settings -> Passcode

- [x] Check that passcode screen is opened using current iPad orientation
- [x] Check that rotating iPad also rotates passcode screen

### Review
Only one developer and one designer are required to review these changes, but anyone can perform the review.

### CODE REVIEW

**Review by SylvesterWilmott — APPROVED** [review]
Looks good! Thanks.

**Review by jleandroperez — APPROVED** [review]
Looks good!!

:shipit:

**Comment by eshurakov** [comment]
Thank you @SylvesterWilmott, @jleandroperez!

**Comment by pachlava** [comment]
[UI Testing] Verified on iPhone XR | iOS 14.3 | SN 4.30

**Pull request merged**
