### PR TITLE
Review your account

### PR DESCRIPTION
**Pull request by eshurakov**
### Fix

In this PR we're adding a screen to review and confirm account details. Logic behind presenting the screen and handling user response is not part of this PR.

Ref. #1086 

@jleandroperez Sorry it's a bit over 500 LOC 🙇 

|||
|-|-|
|Simulator Screen Shot - iPhone 12 - 2021-01-12 at 14 08 54|Simulator Screen Shot - iPhone 12 - 2021-01-12 at 13 09 52|
|Simulator Screen Shot - iPhone 12 - 2021-01-12 at 13 10 05|Simulator Screen Shot - iPhone 12 - 2021-01-12 at 13 10 07|
|Simulator Screen Shot - iPhone 12 - 2021-01-12 at 13 10 00|Simulator Screen Shot - iPhone 12 - 2021-01-12 at 13 10 09|

iPad:

|||
|-|-|
|Simulator Screen Shot - iPad Pro (9 7-inch) - 2021-01-12 at 14 09 55|Simulator Screen Shot - iPad Pro (9 7-inch) - 2021-01-12 at 14 09 48|

### Review
Only one developer and one designer are required to review these changes, but anyone can perform the review.

### CODE REVIEW

**Review by SylvesterWilmott — APPROVED** [review]
UI looks great! Thanks!

**Review by jleandroperez — APPROVED** [review]
Looks sleek!! 

:shipit:

**Comment by eshurakov** [comment]
Thank you @SylvesterWilmott and @jleandroperez!

**Comment by pachlava** [comment]
Fix verified with iPhone XR | iOS 14.3 | SN 4.31

**Pull request merged**
