### PR TITLE
Housekeeping!

### PR DESCRIPTION
**Pull request by jleandroperez**
### Details:
- Encapsulates **Options.firstLaunch**!!!
- Drops Legacy PIN Keychain Entry-Check (It's been at least 7 years!!)
- Drops several unneeded `@available` checks
- Drops Migration Handling from 4.8.0 > 4.8.1 (not needed for fresh installs, and upgrading from <4.7 won't break!)
- Drops dead code!
- Drops manual Equatable implementations!

@aerych Sir!! Can I bug you with this one?

Code deletion week!!! Yayyy!!!

### Test:
1. Fresh install `develop` and login
2. Install this branch on top

- [ ] Verify the app doesn't add a new `Welcome Note` please!

### Test:
1. Fresh install this branch
2. Login!

- [ ] Verify the app adds a `Welcome Note` please 😄 

### Release
These changes do not require release notes.

### CODE REVIEW

**Review by aerych — CHANGES_REQUESTED** [review]
Hola @jleandroperez 👋 

Loving all the red in this one :) 

I tested as described but.... things didn't quite go as expected.  After a fresh install of `develop` I see a new welcome note.  However, after a fresh install of this branch I do not (which seems the opposite of what we're wanting?)

Also, I spotted something curious about the first launch detection/logic and left a note about it.

Back to you sir!

**Comment by jleandroperez** [comment]
@aerych *I'm sorry!!!* I had an unpushed commit 🤦 

Mind running a quick smoke test, just for sanity?

**Thank you sir!!!**

**Review by aerych — APPROVED** [review]
Ah ha! Pesky missing commit! 
Retested after updating and now I see the first launch behavior working as expected.  And I do see the welcome note appearing in the new branch. (It's still there in develop too but 🤷 I guess that's okay?) 

Anyway, :shipit:  when ready!

**Comment by jleandroperez** [comment]
Thanks a lot for testing this one sir!!!

**Pull request merged**
