### PR TITLE
Render Checklists in the Markdown Preview

### PR DESCRIPTION
**Pull request by roundhill**
During testing of #258, users noticed that the markdown preview was not converting the checklist markdown syntax into a checkbox.

This PR fixes that by updating the markdown parser to `Hoextdown` (we used `Hoedown` before), which can parse the checklist syntax into HTML:

simulator screen shot - iphone x - 2019-01-04 at 15 14 24

Unfortunately there's no pod for `Hoextdown`, so I included it in the source of the project (which is the majority of the new code in this PR).

**To Test**
* Create a checklist in the editor.
* Enable markdown for the note from the info panel.
* Swipe to view the markdown preview. The checkboxes should display!
* The checkboxes should _not_ be tappable in the preview.

### CODE REVIEW

**Comment by frosty** [comment]
Just noticed this does introduce a bunch of compiler warnings in the new files. Do we want to do anything about that?

**Comment by roundhill** [comment]
> Just noticed this does introduce a bunch of compiler warnings in the new files. Do we want to do anything about that?

Hmm good catch. Do you think it'd be bad to ignore all warnings from the `Hoextdown` folder code? I can try and fix them but haven't used C in... 20 years :)

**Comment by frosty** [comment]
I think it would be a reasonable compromise for now, particularly as they're part of another project. If we were still using the pod, we'd just be suppressing them with `inhibit_all_warnings!` anyway :)

**Comment by roundhill** [comment]
Thanks @frosty!

**Pull request merged**
