### PR TITLE
Interlinking: Updates Blur

### PR DESCRIPTION
**Pull request by jleandroperez**
### Fix
In this PR we're adjusting the blur translucency.

cc @eshurakov Thank you sir!!
Ref. #914 

### Test
1. Open any note
2. Type `[keyword` to trigger Interlink

- [ ] Verify the Interlink UI now has a super awesome blur!

### Release
These changes do not require release notes.

### CODE REVIEW

**Review by eshurakov — APPROVED** [review]
Bluuuur!

:shipit:

**Comment by jleandroperez** [comment]
Thank youuuuu!!

**Comment by jleandroperez** [comment]
@mokagio Sir!! would it be possible to get a new 4.28 TestFlight build?

**Thank you!!!**

**Comment by mokagio** [comment]
Done 🚀

**Pull request merged**
