### PR TITLE
Merge release 4.32 into trunk

### PR DESCRIPTION
**Pull request by mokagio**
Leaving this as a draft till we actually release it. Still, I'd appreciate a review anyway.

Thanks 🙇‍♂️ .

### CODE REVIEW

**Review by jkmassel — COMMENTED** [review]
This also looks fine but it seems odd that the release build isn't running / being reported?

**Comment by loremattei** [comment]
TBH, it seems odd that the release build job is listed here 🤔 
The HEAD of the branch is not on the tag (which is on `8d55d81`), but on the merge commit, so I expected that the release build job was not listed 🤷‍♂️

**Review by jleandroperez — APPROVED** [review]
Not sure what's going on with the CI, buuut the changes look good!!

:shipit:

**Comment by mokagio** [comment]
@jkmassel @loremattei I think Lore's spot on. Thanks Lore, I've been thinking about this for a few releases, never understood what was going on but never seemed important enough to spend time digging into it.

My guess is that I had a brain fart when creating the branch rule during the `master -> main -> trunk` migration and picked the release build CI job from the list of checks as a required one

image

I've removed it now.

**Comment by mokagio** [comment]
This has now been published on the Store: Marking it "Ready for Review" and merging it.

**Pull request merged**
