### PR TITLE
Nü Note Options: Mark II

### LINKED ISSUE #715: Sync: When the note dialog is open, remote changes to published/pinned/markdown status are synced but not reflected
### Expected

I expect that remote changes to a note's published/pinned/markdown status changes remotely will be immediately reflected in the app.

### Observed

When I change a note's published/pinned/markdown status remotely, the change syncs immediately in the iOS app but the button for that status isn't changed until I close and reopen the note dialog.

This is most obvious for the published status, because the public link is updated (added or removed) immediately but the Publish/Published button doesn't change.

### Reproduced

1. In the iOS app, open a note.
2. Tap the `i` icon to open the note dialog.
3. On another device, publish the note. Notice that the iOS app dialog immediately updates with the public link, but it still shows `Publish` (as if the note weren't published).
4. In the iOS app, close the dialog and reopen it. Notice that now the dialog shows the `Published` button as expected.

Make|Model|iOS Version|App Version
-|-|-|-
Apple|iPhone XS|13.3.1|4.17.0.0 TestFlight Beta

### PR DESCRIPTION
**Pull request by jleandroperez**
### 🛑  Important
Don't merge until #906 #907 #909 and #910 are ready: everything must be merged in a single shot!

### Details
- Implements **EntityObserver** in the Options UI: we'll dynamically refresh everything whenever the associated Note is updated.
- Implements handlers several actions:
  - **Pin**
  - **Markdown**
  - **Copy Interlink**
  - **Publish** + **Copy Public Link**
- Dead code has been commented out (and removed in a follow up PR!)

@etoledom @guarani Gentlemen, may I bug you with this one?
**Thanks a looooot!!!**

Closes #715
Ref. #763
Ref. #863 

---

### Test: Dynamic Refresh      :::      @guarani 👇👇👇 **Thank you Paul!!!**
1. Open the same Note in iOS + another client (web or macOS!)
2. In iOS: Press the top `( i )` icon to reveal the Options

- [x] Verify that toggling the **Pin** / **Markdown** / **Published** flags in your second client causes iOS to refresh its UI

### Test: Markdown      :::      @guarani 👇👇👇 **Thank you Paul!!!**
1. Open any note and press over the top `( i )` icon
2. Disable Markdown and press **done** to dismiss
3. Reopen the Note Options
4. Enable Markdown and press **done** to dismiss

- [x] Verify that as soon as the Options UI is gone, the view bounces horizontally (revealing the Markdown Preview UI)
- [x] Verify that if you **add a new Note**, the **Markdown** flag of your last selection will be applied (On or Off by default!)

### Test: Copy Interlink      :::      @guarani 👇👇👇 **Thank you Paul!!!**
1. Open any note and press over the top `( i )` icon
2. Press over the **Copy Interlink** row

- [x] Verify that **Pasting** over the editor inserts a link to the note you're currently editing!

---

### Test: Pinning      :::      @etoledom  👇👇👇 **Thank you Eduardooooo!!!**
1. Open any note and press over the top `( i )` icon
2. Press over the **Pin to Top** row

- [x] Verify the Note ends up pinned!

### Test: Publishing      :::      @etoledom  👇👇👇 **Thank you Eduardooooo!!!**
1. Open any note and press over the top `( i )` icon
2. Enable the `Publish` switch

- [ ] Verify the row below reads as `Publishing...` and cannot be selected
- [ ] Verify that after a while the row belows reads as `Copy Link`
- [ ] Verify that pressing `Copy Link` copies the associated Note URL into the Pasteboard
- [ ] Verify that pressing the `Publish` switch again causes the text `Unpublishing...` in the row below
- [ ] Verify that (shortly after) the row below reads as `Copy Link`, but cannot be selected

### Release
These changes do not require release notes.

### CODE REVIEW

**Review by etoledom — COMMENTED** [review]
> Test: Publishing

❌ Verify the row below reads as Publishing... and cannot be selected

After switching to Publish, the row bellow didn't change. It only changed after I closed and opened the Options screen again. Also after moving the switch a few times, then the row bellow started to change as expected.

Never saw the "Copy Link" text active.

publish_switch

**Comment by jleandroperez** [comment]
@etoledom **Thank you for catching that!!!**

Mind taking another peek? (should be good now!!). Comment aside, we're having backend issues, the publish queue has a 14 minutes delay (so if it doesn't get to `Published`, it's definitely because of that).

Thanks in advance!!!

**Review by guarani — APPROVED** [review]
Tested my cases and working great, thanks @jleandroperez

**Comment by jleandroperez** [comment]
Thanks a lot Paul!!

**Comment by jleandroperez** [comment]
Hope you don't mind @etoledom !!! merging this one since it's blocking few other PR's.
(Publish row behavior has been patched up!!)

Thank you both **A LOT** for all your help!!!

**Pull request merged**
