### PR TITLE
Merge release 4.29 into trunk

### PR DESCRIPTION
**Pull request by mokagio**

### CODE REVIEW

**Review by jleandroperez — APPROVED** [review]
:shipit: sir!

**Comment by jleandroperez** [comment]
@mokagio Should we close this one Gio? (Thank yoou!!)

**Comment by mokagio** [comment]
Hey @jleandroperez.

Sorry about leaving this hanging here. I keep meaning to look into why CI doesn't report the completion of the build step but never get onto it.

**Comment by jleandroperez** [comment]
Thank you Gio!!

**Pull request merged**
