### PR TITLE
Fix widget note or note list leakage when pin lock is enabled

### LINKED ISSUE #1445: [Widgets] Possible to see any note content with passcode active
I'm not exactly sure this is a bug. By adding widgets, the user already takes a step back from their notes privacy.

### Expected
Again, it's hard to say it's definitely expected. This is something that wasn't an option before. 

If the user has a passcode active, previously it meant that notes can't be viewed without knowing the password. Now it's possible with widgets.

### Observed
`Note` widget will allow to change the note selected for display without asking for passcode (first seconds are just showing the app has a passcode active):

https://user-images.githubusercontent.com/73365754/134319491-82b7fa69-f6d8-45cc-a034-a571e6d75f8d.MP4

### Reproduced
1. Activate passcode in the app
2. Add a `Note` widget
3. Kill the app to make sure passcode will be required from now on
4. You can change the note selected for display in `Note` widget (and see the note), which bypasses the need to enter a passcode to see the note.

Make|Model|iOS Version|App Version
-|-|-|-
iPhone|XR|14.7.1|4.45.0.0

### PR DESCRIPTION
**Pull request by jimlearning**
### Fix

It's possible to see all your notes from widgets even though pin lock(password) is active.

1. Turn on pin lock.
2. When choose note widget or note list in widgets center, the snapshot of note or note list is shown without protected.
3. When display a note widget or note list widget, the note or note list is shown without protected.
4. When edit a note widget, all note list can be seen, and any note can be selected then displayed in the note widget.

In this PR I have added pinLockIsEnabled state to check all notes or note list in widgets, just like the way when logged out. When pinLockIsEnabled is true, the note or note list is hidden, otherwise it is displayed.

fixes #1445 

### Test

1. Turn on pin lock.
2. When choose note widget or note list in widgets center, the snapshot of note or note list will be shown as "Unlock to see your note/note list".
3. When a note widget or note list widget added, the note or note list will be shown as "Unlock to see your note/note list".
5. When edit a note widget, the note list will not be shown and selected.
6. Turn off pin lock, the note widget or note list widget will be shown normally.

### Review
***(Required)*** Add instructions for reviewers.  For example:
> Only one developer and one designer are required to review these changes, but anyone can perform the review.

### Release
***(Required)*** Add a concise statement to `RELEASE-NOTES.txt` if the changes should be included in release notes. Include details about updating the notes in this section. For example:
> `RELEASE-NOTES.txt` was updated in d3adb3ef with:
> 
> > Added markdown support

### CODE REVIEW

**Comment by jleandroperez** [comment]
Hey there @jimlearning,

Thank you for your contribution! I'm afraid this feature would break current workflows, for people who use pinlock code, and keep groceries in their springboards (such as myself!).

**Comment by jimlearning** [comment]
> Hey there @jimlearning,
> 
> Thank you for your contribution! I'm afraid this feature would break current workflows, for people who use pinlock code, and keep groceries in their springboards (such as myself!).

Thank you for your reply. I've added a switch that lets the user decide if the widgets should be locked as well. Not locked by default.

**Comment by jleandroperez** [comment]
@jimlearning Thank you so much for your contribution and for taking the time to propose this feature! 

The team has carefully reviewed the PR, and while we really appreciate the thought and effort you put into it, we’ve decided not to merge it at this time.

**Comment by jleandroperez** [comment]
Adding a bit of context:

We believe that this concrete issue should be addressed via a change in the way the Notes Widget works. 

Everytime a new Note is selected, whenever the app has a pincode set, the Widget itself should display a 'Locked' placeholder, directing the user to launch the app, to Unlock Access to such note.

This is a much simpler approach, doesn't involve 'Setting discoverability' issues, and would preserve current flows.

**Comment by jimlearning** [comment]
> Adding a bit of context:
> 
> We believe that this concrete issue should be addressed via a change in the way the Notes Widget works.
> 
> Everytime a new Note is selected, whenever the app has a pincode set, the Widget itself should display a 'Locked' placeholder, directing the user to launch the app, to Unlock Access to such note.
> 
> This is a much simpler approach, doesn't involve 'Setting discoverability' issues, and would preserve current flows.

Thanks. I'm glad to hear the team is considering this issue, and can't wait to see the new feature rolled out!

**Pull request closed without merging**
