### PR TITLE
Apply minimum cell height in condensed list mode

### LINKED ISSUE #1045: Condensed Mode: Minimum Height
### Details:
Our Notes List should display cells that are, at least, 44pt height whenever condensed mode is enabled.

Ref.:

### PR DESCRIPTION
**Pull request by eshurakov**
### Fix
In this PR we're applying minimum height of 44pt to the note list cells in condensed mode.
In addition this PR fixes incorrect separator margins. This issue happens for reused cells when note list is scrolled.

Closes #1045

|Before|After|
|-|-|
|Simulator Screen Shot - iPhone 12 - 2021-01-12 at 13 51 07|Simulator Screen Shot - iPhone 12 - 2021-01-12 at 16 11 43|

### Test
1. Enable condensed mode
2. Open note list

- [ ] Check the cells height is at least 44pt
- [ ] Scroll the list back and forth. Check that separators are always aligned with the text

### Review
Only one developer and one designer are required to review these changes, but anyone can perform the review.

### Release
`RELEASE-NOTES.txt` was updated in 1a79bb2b with:
> Updated minimum row height when note list is in condensed mode #1045

### CODE REVIEW

**Comment by SylvesterWilmott** [comment]
Thanks for the fix! In the attached screenshot, it looks like the note title is not vertically centered within each row. Can we try to center it?

**Comment by eshurakov** [comment]
@SylvesterWilmott, good point! The content is now centred, I updated the screenshot as well.
Thank you!

**Review by SylvesterWilmott — APPROVED** [review]
Thanks @eshurakov !

**Review by jleandroperez — APPROVED** [review]
Nice @eshurakov !!!

:shipit:

**Comment by eshurakov** [comment]
Thank you @SylvesterWilmott and @jleandroperez!

**Comment by pachlava** [comment]
[texting] Verified the feature on iPhone XR | iOS 14.3 | SN 4.31
Did not measure the cells height, but they definitely are higher than in 4.30

**Pull request merged**
