### PR TITLE
Merge release 4.25 into trunk

### PR DESCRIPTION
**Pull request by mokagio**
I'm not sure why there are so many commits in the log. It looks like there are also commits related to v4.24. 

I tried a merged locally and confirmed it works, so I guess we're still good? 🤔

### CODE REVIEW

**Review by jleandroperez — APPROVED** [review]
Looks super, thank you Gio!!

:shipit:

**Comment by mokagio** [comment]
image

I wouldn't normally do this, but I already merged `release/4.25` into `develop`, #898, and there already is a tag for 4.25 so little harm is done by this other than making the log a bit messy in the interest of avoiding an history rewrite which would make it confusing if we ever went back and looked at this and its sister PR against `develop`.

**Review by jkmassel — APPROVED** [review]

**Comment by mokagio** [comment]
That Release Build CircleCI task has been stuck there for _days_... I'd really like to chase down the reason why before merging this.

**Comment by mokagio** [comment]
I haven't had the time to look into this yet.

Merging just to avoid things getting stuck later this week for 4.26

**Pull request merged**
