### PR TITLE
Tags editor, bubblified: MK2

### PR DESCRIPTION
**Pull request by eshurakov**
### Details
In this PR:
* Tags in the editor are shown as bubbles
* SPTagView.m  is gone and replaced with TagView.swift
* Use auto layout for tags editor
* Autocomplete is temporarily gone and will be restored in one of the next PRs.

Apologies about the size of this PR 🙇 

Ref: #990

### Screenshots

|||
|-|-|
|Simulator Screen Shot - iPhone 12 - 2021-02-15 at 14 36 11|Simulator Screen Shot - iPhone 12 - 2021-02-15 at 14 36 15|

### Test
Run a quick smoke around tags in the editor. Except the change in design and missing autocomplete the behaviour should be the same.

### Review
Only one developer and one designer are required to review these changes, but anyone can perform the review.

### CODE REVIEW

**Comment by SylvesterWilmott** [comment]
Looks great!

My only feedback is that the note content can get quite near to the tags area. Visually, the tags area appears as an invisible bar. The content of the note should be distanced from the bar when scrolling so it pushes the tags off the screen. See below of illustration:

Can we add a space of 16pt above the pink area so that the note content cannot appear this close to the tags area?
Screenshot 2021-02-15 at 14 52 46

**Comment by eshurakov** [comment]
> Can we add a space of 16pt above the pink area so that the note content cannot appear this close to the tags area?

Thank you @SylvesterWilmott, I've added additional space between text and tags area.

**Comment by jleandroperez** [comment]
Awesome work @eshurakov !!

✅ Code looks super sharp
✅ Reacts super to Dynamic Fonts
✅ Also reacts well to Dark Mode

I found two tiny details, **good to address in a follow up** (given the size of this PR already!)

### RTL Pinning
Note that the Tags Editor (in develop / RTL mode) was pinned to the right hand side:

Before|Now
-|-
|

### Crowded Editor
Note that in develop the `Add Tag` placeholder never goes offscreen:

#### Old
https://user-images.githubusercontent.com/1195260/108076569-5623a700-704a-11eb-83df-8e2da34581c6.mp4

#### New
https://user-images.githubusercontent.com/1195260/108076583-5b80f180-704a-11eb-90ea-ba5e480cefcc.mp4

**Review by jleandroperez — APPROVED** [review]
:shipit: (As mentioned above, good to address the pendings elsewhere, 100% up to you!)

**Comment by eshurakov** [comment]
Thank you @jleandroperez, I've added the issues you found to the project issue #1067

**Comment by jleandroperez** [comment]
@eshurakov confirming the rotation freeze is fixed! :shipit:

**Review by SylvesterWilmott — APPROVED** [review]

**Comment by eshurakov** [comment]
Thank you!

**Comment by pachlava** [comment]
[testing] fix/feature verified on:

model | iOS | Simplenote
-|-|-
iPhone XR | 14.4 | 4.33.0.0
iPad Pro 11” Sim | 14.4 | 4.33.0.0

**Pull request merged**
