### PR TITLE
fix-191-character-count

### PR DESCRIPTION
**Pull request by LispLY**
[issue 191](https://github.com/Automattic/simplenote-ios/issues/191)
Fixing character count in Chinese and Japanese.Sorry but Korean not included.

In China and Japan we usually count words by character so I made this fix.
In Korea things maybe like English or other Latin languages.

When  word count needed, determine the language first. If it's "zh"(Chinese) or "ja"(Japanese), we use the new characterCount, else we just use the old wordCount method.
I was tried to code in Objective-C but it was a little hard because NSCharacterSet is  an NSObject rather than a real Set. 

To be fixed:
1. Korean.
2. When there is not a dominant language, like 40% English plus 60% Japanese, the dominant language would be "undefined", and we just use the old wordCount method. Now we test the language by whole string. Testing the language by sentence may help but it is a little expensive.
3. Dominant language testing is only available since iOS 11, so we use the old way in iOS 10 and earlier versions.

### CODE REVIEW

**Comment by roundhill** [comment]
How about we just show both word and character count like we recently did for the Android app?

https://user-images.githubusercontent.com/3122461/43176802-f2163faa-8ff7-11e8-8f61-e17800b4f15f.png

**Comment by LispLY** [comment]
Showing both word and character count would be good and I am going to try.

BTW the word count in Android version doesn't work properly either when there's Chinese character.
Usually we count every single Chinese character as a "word" when we do word count. (Both Pages and MS Word do it this way. )

**Comment by LispLY** [comment]
I've pushed the new version with character count and word count.
Now we need the localized string @"%d Characters" (Number of Characters in a note).

**Comment by roundhill** [comment]
@LispLY sorry for the delay in getting back to you. I think this is looking good. Is there any chance you can add the locale-specific thousands separator to the counts?

screen shot 2018-11-19 at 2 00 09 pm

So that would be `2,175` and `17,052` for English.

**Comment by LispLY** [comment]
@roundhill OK, I'll try.

**Comment by LispLY** [comment]
@roundhill Locale-specific thousands separator is added.
Now￼￼ it's like:

US￼￼:
image

Italy:
image

**Comment by roundhill** [comment]
Wonderful! Thanks so much for your hard work @LispLY. :shipit:

**Pull request merged**
