### PR TITLE
Merge 4.45.1 hotfix to 4.46

### PR DESCRIPTION
**Pull request by oguzkocer**
The merge conflict was for the versions in `config/Version.Public.xcconfig` & `fastlane/Deliverfile` - I've selected the `4.46` versions for both.

This is my first hotfix and although I think I got the steps right, I'd like to verify them with @Automattic/owl-team before publishing the binary. Here is what I did:

1. Created the `release/4.45.1` branch by running `bundle exec fastlane new_hotfix_release version:4.45.1`
2. Developers merged the fix into `release/4.45.1`
3. I created a new version in App Store Connect for `4.45.1`
4. Ran `bundle exec fastlane deliver --skip_screenshots` so metadata fields would be updated. This should upload the metadata for `4.45` which I believe is what we want. [Here is the diff between `4.45` & `4.45.1`.](https://github.com/Automattic/simplenote-ios/compare/4.45...release/4.45.1?expand=1)
5. I kept the original release note for `4.45` which was `Added home screen widgets` and added `Fixed an iOS 12 specific crash when app launched` (grabbed from #1463). Of course this addition will only be visible for English users since we don't have translations for this release note.
6. Ran `bundle exec fastlane trigger_release_build branch_to_build:release/4.45.1` to upload the build
7. Tested it through Testflight
8. Submitted the binary

### CODE REVIEW

**Comment by AliSoftware** [comment]
At first glance the steps described looks correct to me.

(To be pedantic, step 6 should technically have been `fastlane finalize_hotfix_release` if we want to follow the process strictly; though the only thing that lane does is perform some prechecks… then run the `trigger_release_build` lane that you called directly. So basically that's the same thing after all and not a problem.)

I'll let Gio review and do the final approval during his day because I'm on phone and didn't check the diff, but from the PR description at least the process LGTM.

**Comment by oguzkocer** [comment]
I should have realized there was a `finalize_hotfix_release` lane 🤦 Thanks @AliSoftware 🙇

**Review by mokagio — APPROVED** [review]
👌 on the steps you took @oguzkocer 

On question. You say:

> I kept the original release note for 4.45 which was `Added home screen widgets` and added `Fixed an iOS 12 specific crash when app launched` (grabbed from iOS 12 crash hot fix #1463). Of course this addition will only be visible for English users since we don't have translations for this release note.

I don't see that change in the diff on GitHub, though:

image

I don't think that's a blocker, and realize it might have referred to a change done on App Store Connect only.

I disabled the auto-merge, just in case you intend that to be part of the PR. Together with this approval, it will give us the chance to either merge as is (= the change was meant for ASC only) or push a new commit and merge afterwards (= the change was meant for the `.txt` file in the repo).

I'm happy either way. 👍 Thank you for this.

**Comment by oguzkocer** [comment]
@mokagio I added the release note to ASC only because I felt adding it to the metadata would create inconsistency across locales. I don't feel strongly about it though, so if you think we should have it, I don't mind it.

**Comment by mokagio** [comment]
Nah, no worries. :shipit:

**Pull request merged**
