### PR TITLE
Updates Translations

### PR DESCRIPTION
**Pull request by jleandroperez**
### Fix
In this PR we're updating the Localizations. For the record:

1. I've edited `fastlane/Fastfile` and commented out L205-212 and L179
2. Executed `bundle exec fastlane finalize_release`

@mokagio Would it be possible to confirm if doing this was required, or it's just part of the regular release process?
I **think** it wasn't really needed?

Thanks in advance!!

### Test
- [ ] Smoke test Simplenote and make sure everything looks good!

### CODE REVIEW

**Comment by dangermattic** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This PR is larger than 500 lines of changes. Please consider splitting it into smaller PRs for easier and faster reviews.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by charliescheer — APPROVED** [review]

**Comment by jleandroperez** [comment]
TY!

**Comment by mokagio** [comment]
@jleandroperez the diff looks good—assuming the desired result was to get the latest changes from GlotPress into the app.

I was going to ask whether you tried running `new_beta`, but upon looking at the source I noticed a mistake, so even if you had tried, it would have failed.

Leaving aside that temporary issue, generally, we shouldn't need to manually download strings, and are better off triggering new betas to update them.

**Comment by jleandroperez** [comment]
Thank you @mokagio !! Next time we won't be manually updating strings, then.

I've used a patched version of `finalize_release`.

Hope you're doing great sir!!

**Pull request merged**
