### PR TITLE
Fix/build ITC lane

### PR DESCRIPTION
**Pull request by loremattei**
### Fix
This PR fixes the `build_and_upload_itc` lane adding the missing automation for certificates and profiles handling. 

### Test
1. Run `bundle exec fastlane build_and_upload_itc`.
2. Verify that `gym` finishes successfully and that the upload to iTC starts. It will fail because the version is already present, but this is fine as the current failing phase is `gym`. If iTC recognizes that the version is already present, it means that the build and signing processes finished successfully.

### Review
Only one developer is required to review these changes, but anyone can perform the review.

### Release
These changes do not require release notes.

### CODE REVIEW

**Comment by loremattei** [comment]
Simplenote iOS signing makes me mad :-) 
I got a signing error I never had before and I thought I actually missed something because I saw a Slack thread where you fixed something about this...
And actually, adding that line fixed the error for me 🤔

**Comment by loremattei** [comment]
Looking at the error... it looks like you may be building the wrong configuration. I just pushed an update to force the right one in Fastlane. 
Let's see if this solve the issue.

**Comment by jkmassel** [comment]
I added a couple of little changes to this – I think the root issue is that we weren't using the `match` signing certificates – now the project is set to, and it builds perfectly.

You can test whether this works by temporarily relocating everything in your `~/Library/MobileDevice/Provisioning Profiles/` directory – that'll make the `build_and_upload_itc` lane download the right certificates. 

I think we'll probably need a third set of eyes to 👍 this now that I messed with it – @oguzkocer, would you be up for it? :)

**Comment by loremattei** [comment]
@oguzkocer the login `match` is looking for is your apple one. It's used to check IDs, certs and profiles.

**Comment by loremattei** [comment]
@jkmassel it worked as expected for me. 👍

**Comment by oguzkocer** [comment]
I do have an Apple ID that I used for iOS development when I joined but I don't know if that'll work.

@jkmassel Do you need me to give this a try?

**Comment by jkmassel** [comment]
@oguzkocer – sure! You're an admin on the project, so it should work fine for you if you use your a8c Apple ID :)

**Pull request merged**
