### PR TITLE
Fixed Infinite Wrong Passcode bug

### PR DESCRIPTION
**Pull request by shabirjan**
Fixed Issue 132-Infinite wrong Passcode attempts

### CODE REVIEW

**Comment by jleandroperez** [comment]
Hello there @shabirjan,

Thanks for contributing to Simplenote!. Would it be possible to revert all of the alignment to it's original style?. We use standard Objective C alignment (no indentation for each method).

Thanks in advance!

**Comment by shabirjan** [comment]
Sure i ll do that and push again :)

**Comment by shabirjan** [comment]
Hi @jleandroperez 
I have fixed the code indentation bug mentioned by you.

**Comment by jleandroperez** [comment]
Thanks for helping us out @shabirjan!!

:shipit:

**Comment by shabirjan** [comment]
Welcome :)

**Pull request merged**
