### PR TITLE
Contextual Menu Support

### PR DESCRIPTION
**Pull request by jleandroperez**
### Details:
In this PR we're implementing the contextual UITableView / UIMenu API, which replaced the legacy 3d Touch API(s).

@etoledom Sir!! would you be game for a quick PR?
Thanks in advance!!

Ref. #863

### Test: All Notes
1. Log into your account
2. Select All Notes
3. Long press over any Note in your List

- [x] Verify that a Preview with actions at the bottom shows up
- [x] Verify that pressing the Preview pushes the Editor
- [x] Verify that **Copy Link** places in the Pasteboard a link to the selected note (paste elsewhere!)
- [x] Verify that pressing **Share** opens the Share Sheet
- [x] Verify that pressing **Delete** trashes the selected note

### Test: Trash
1. Log into your account
2. Open the Trash
3. Long press over any trash ed notes

- [x] Verify nothing happens!

### Release
These changes do not require release notes.

### CODE REVIEW

**Review by etoledom — APPROVED** [review]
Nice PR @jleandroperez ! Working great 🎉 

One small detail I noticed while deleting notes:
The behaviour seems to be different than deleting the note with the normal cell buttons, it will remove the cell and it seems to be replaced by other random note, without animations. While the expected behaviour would be to see the deletion animation and see the cell disappear.

deleting


Approving since everything (else) I working as expected ✅

**Comment by jleandroperez** [comment]
Thank you for testing this one @etoledom !!!

Quick Q sir!! is it possible that video was taken on the iOS Sim? (can't repro on the actual device, only happens in the simulator on my end).

**Comment by etoledom** [comment]
@jleandroperez - it was on an iPhone 7 device running iOS13.
I hope that helps!

**Comment by jleandroperez** [comment]
Thank you @etoledom !!! Bug confirmed in iOS 13 (simulator). 

For the time being, I've disabled the `Delete` action on iOS 13, since this has the shape of a SDK / animation glitch (afaik solved in 14!).

**Again, thank you sir!!**

**Pull request merged**
